services:
  grpc:
    logging:
      driver: "json-file"
      options:
        max-size: 20m
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    command: ["/server"]
    restart: always  # Перезапускать контейнер в случае падения
    networks:
        - grpccache_network  # Указана только внешняя сеть
networks:
  grpccache_network:
    external: true
    driver: overlay
    attachable: true
